from enum import Enum


class GameState(Enum):
    IDLE = "idle"
    REGISTERING = "registering"
    REGISTRATION_CLOSED = "registration_closed"
    RUNNING = "running"
    PAUSED = "paused"
    ENDED = "ended"


class Side(Enum):
    DAN = "dan"
    SOI = "soi"
    TRUNG_LAP = "trung_lap"


class WerewolfPhase(Enum):
    WAITING = "waiting"
    SETTING = "setting"
    NIGHT = "night"
    DAY = "day"
    ENDED = "ended"


class RoleType(Enum):
    DAN_LANG = "dan_lang"
    SOI_THUONG = "soi_thuong"
    BAO_VE = "bao_ve"
    KE_HAP_HOI = "ke_hap_hoi"
    MUC_SU = "muc_su"
    TIEN_TRI = "tien_tri"
    THAY_BOI = "thay_boi"
    KE_TINH_GIAC_GIUA_DEM = "ke_tinh_giac_giua_dem"
    NHA_NGOAI_CAM = "nha_ngoai_cam"
    CANH_SAT_TRUONG = "canh_sat_truong"
    PHAP_SU = "phap_su"
    KE_BAO_THU = "ke_bao_thu"
    XA_THU = "xa_thu"
    NHA_BAO = "nha_bao"
    LOLI = "loli"
    NGUOI_BENH = "nguoi_benh"
    NGUOI_GAC_DEM = "nguoi_gac_dem"
    KE_HOANG_TUONG = "ke_hoang_tuong"
    NGUOI_NOI_TIENG = "nguoi_noi_tieng"
    NGUOI_BI_TAY_CHAY = "nguoi_bi_tay_chay"
    KE_SONG_SOT = "ke_song_sot"
    NGUOI_CAM_BOM = "nguoi_cam_bom"
    KE_HOI_LO = "ke_hoi_lo"
    KE_NGHIEN_CO_BAC = "ke_nghien_co_bac"
    KE_DA_NGHI = "ke_da_nghi"
    KE_THAM_DO = "ke_tham_do"
    KE_DIEU_HUONG_DU_LUAN = "ke_dieu_huong_du_luan"
    KE_KE_THUA = "ke_ke_thua"
    NGUOI_VAN_DONG_HANH_LANG = "nguoi_van_dong_hanh_lang"
    NGUOI_GAY = "nguoi_gay"
    YANDERE = "yandere"
    MEO_BEO = "meo_beo"
    KE_TU_DAO = "ke_tu_dao"
    THAM_TU_TU = "tham_tu_tu"
    THAM_PHAN = "tham_phan"
    SIMP = "simp"
    NGUOI_TIEN_PHONG = "nguoi_tien_phong"
    KE_CHAN_DON = "ke_chan_don"
    KE_GHI_HAN = "ke_ghi_han"
    DAO_PHU = "dao_phu"
    NGUOI_NHAN_NHIN = "nguoi_nhan_nhin"
    SOI_PHAP_SU = "soi_phap_su"
    SOI_GIAN_DIEP = "soi_gian_diep"
    SOI_SAT_THU = "soi_sat_thu"
    SOI_BANG = "soi_bang"
    SOI_GOKU = "soi_goku"
    SOI_HAC_AM = "soi_hac_am"
    SOI_TICH_LUY = "soi_tich_luy"
    SOI_CUOP_DANH_TINH = "soi_cuop_danh_tinh"
    SOI_MACH_LEO = "soi_mach_leo"
    SOI_PHAN_DONG = "soi_phan_dong"
    SOI_HO_VE = "soi_ho_ve"
    SOI_DAT_BAY = "soi_dat_bay"
    SOI_CAM_TU = "soi_cam_tu"
    SOI_GIAN_LAN = "soi_gian_lan"
    SOI_CO_KHIEN = "soi_co_khien"
    SOI_KET_GIOI = "soi_ket_gioi"
    SOI_TU_BAN = "soi_tu_ban"
    SOI_TINH_BAN = "soi_tinh_ban"
    KE_DAT_BOM = "ke_dat_bom"
    KE_PHONG_HOA = "ke_phong_hoa"
    LOLICON = "lolicon"
    SOI_CO_DOC = "soi_co_doc"
    KE_NOI_DOI = "ke_noi_doi"
    THICH_KHACH = "thich_khach"
    CON_QUA = "con_qua"
    KE_TIM_SU_THAT = "ke_tim_su_that"
    SAT_THU = "sat_thu"
    KE_TANG_HINH = "ke_tang_hinh"
    KE_DANH_BAC = "ke_danh_bac"
    KE_PHAN_DON = "ke_phan_don"
    CAO_BOI = "cao_boi"
    AYANOKOJI = "ayanokoji"
    KE_TAM_LY_YEU = "ke_tam_ly_yeu"
    VUA_LI_DON = "vua_li_don"
    KIM_JONG_UN = "kim_jong_un"
    GIAN_THUONG = "gian_thuong"
    MA_CA_RONG = "ma_ca_rong"
    KE_CAT_DIEN = "ke_cat_dien"
    KE_NOI_HON = "ke_noi_hon"
